branches:
  only:
    - /\d+\.\d+\.\d+/
language: python
python: "3.6"
install:
  - cd frontend
  - npm install
script:
  - npm run build
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z script.module.web-pdb
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the Kodi official repo
  - provider: script
    script: submit-addon -r repo-scripts -b krypton --pull-request script.module.web-pdb
    on:
      tags: true
notifications:
  email: false
