branches:
  only:
    - /\d+\.\d+\.\d+/
language: python
python: "3.6"
env:
  - ADDON_ID=script.module.web-pdb
install:
  - cd frontend
  - npm install
script:
  - npm run build
after_success:
  - cd $TRAVIS_BUILD_DIR
  - echo "SHA1 hashes for minified files:"
  - sha1sum script.module.web-pdb/libs/web_pdb/static/bundle.min.js
  - sha1sum script.module.web-pdb/libs/web_pdb/static/styles.min.css
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z $ADDON_ID
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the Kodi official repo
  - provider: script
    script: submit-addon -r repo-scripts -b krypton --pull-request $ADDON_ID
    on:
      tags: true
notifications:
  email: false
