branches:
  only:
    - /v\.\d+\.\d+\.\d+/
language: python
python: "2.7"
install: true
script: echo "Nothing to build"
before_deploy:
  - wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/deploy_addon.py
  - python deploy_addon.py -z
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the Kodi official repo
  - provider: script
    skip_cleanup: true
    script: python deploy_addon.py -k repo-scripts -b jarvis
    on:
      tags: true
notifications:
  email: false
